### ISSUE TITLE
Add raycast support

### ISSUE THREAD

**Issue by spite** [spite/THREE.MeshLine#8]
Make something similar to THREE.Line, accounting for the size attenuation flag, variable width, etc. features.

**Comment by spite** [comment]
Use https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/src/objects/Line.js#L26 as reference.

**Comment by inDigiNeous** [comment]
Hey spite, Sakari here from Vizor.io, we are in the process of adding THREE.MeshLine support into our editor, would need support for raycasting in order to pick objects created with MeshLine .. any progress in implementing this ?

Thanks, also thanks for this plugin :)

**Comment by inDigiNeous** [comment]
Just to let you know, I'm looking into implementing this.

**Comment by spite** [comment]
Haven't had any time to even look into it :( 
If you are going to implement, that'd be a very welcome addition

**Comment by inDigiNeous** [comment]
Ok, yeah starting to actually implement this right now, gonna use the Line method as a reference.

**Comment by inDigiNeous** [comment]
So yeah. What I did as an naive implementation, I took the raycast method from the Three.Line, and just modified for that to work. That implementation required the worldMatrix variable to be passed in, so I had to pass that manually in there.

But it seems to work. See the final implementation added to vizor here: https://github.com/vizorvr/vizor/blob/develop/browser/vendor/spite/THREE.MeshLine.js

Not gonna do a pull request, because of the worldMatrix that has to be passed in. But maybe you can copy it from there and adapt. 

Also, here is a testcase: https://github.com/inDigiNeous/threejs/blob/master/test_meshline_raycast.html
(Just clone the whole threejs dir to test it)

**Comment by jacobhamblin** [comment]
I'm trying to implement this for my project, too. I didn't get your example working @inDigiNeous - if you don't mind me asking, where does MeshLine get the function setMaterial, used [here](https://github.com/inDigiNeous/threejs/blob/master/js/test_meshline_raycast.js#L174)? Doesn't seem like it's causing my issue with raycasting, but not sure what it is.

**Comment by kappys1** [comment]
Hi!

is possible to doing raycaster? 
if is possible can you show me in an example?

**Comment by spite** [comment]
You have a forked version in the previous comment, you could try that.
Another option is rendering to a color buffer and do color picking, like in https://threejs.org/examples/?q=inter#webgl_interactive_cubes_gpu

**Comment by kappys1** [comment]
okey! 

It's working now but I have a problem, The raycaster intersects only when my MeshLines is near of my axis Helper in the scene, I want to say when is near (0,0,0) axis. 
I'm doing that my mesh lines follow one track and when it is far, I can't intersect them... 

I test this with two perspective cameras, one viewing all scene and the other follow the track and lines, but I intersects the lines in the same point, near of 0,0,0

do you have any idea because it isn't possible?

**Comment by kappys1** [comment]
Okey! 
I try to replicate these example with your library but I don't work
@spite Can you get my an example with this in JSFIddle or plunkr with advance Mode? 

Thanks

PD: I'm spanish and catalan as you, if you want we can speak better in catalan for email! 

Thanks
